version: "3.8"

services:
  zipkin:
    image: openzipkin/zipkin
    mem_reservation: 700m
    ports:
      - "9411:9411"
    networks:
      - eazybank-network

  configserver:
    image: densoftdev/configserver:latest
    mem_reservation: 700m
    ports:
      - "5003:5003"
    depends_on:
      - zipkin
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    networks:
      - eazybank-network
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  eurekaserver:
    image: densoftdev/eurekaserver:latest
    mem_reservation: 700m
    ports:
      - "5004:5004"
    networks:
      - eazybank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:5003/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/



  accounts:
    image: densoftdev/accounts:latest
    mem_reservation: 700m
    ports:
      - "5000:5000"
    networks:
      - eazybank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:5003/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:5004/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  loans:
    image: densoftdev/loans:latest
    mem_reservation: 700m
    ports:
      - "5001:5001"
    networks:
      - eazybank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:5003/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:5004/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  cards:
    image: densoftdev/cards:latest
    mem_reservation: 700m
    ports:
      - "5002:5002"
    networks:
      - eazybank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:5003/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:5004/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  gatewayserver:
    image: densoftdev/gatewayserver:latest
    mem_reservation: 700m
    ports:
      - "5005:5005"
    networks:
      - eazybank-network
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:5003/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:5004/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/


      
networks:
  eazybank-network: