version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - eazybank-network
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - eazybank-network

  zipkin:
    image: openzipkin/zipkin
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "9411:9411"
    networks:
      - eazybank-network


  configserver:
    image: densoftdev/configserver:latest
    ports:
      - "5003:5003"
    networks:
      - eazybank-network
    depends_on:
      - zipkin
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  eurekaserver:
    image: densoftdev/eurekaserver:latest
    ports:
      - "5004:5004"
    networks:
      - eazybank-network
    depends_on:
      - zipkin
      - configserver
    deploy:
      resources:
        limits:
          memory: 700m
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 10
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:5003/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/


  accounts:
    image: densoftdev/accounts:latest
    mem_reservation: 700m
    ports:
      - "5000:5000"
    networks:
      - eazybank-network
    depends_on:
      - zipkin
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 90s
        max_attempts: 5
        window: 240s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:5003/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:5004/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/


  loans:
    image: densoftdev/loans:latest
    mem_reservation: 700m
    ports:
      - "5001:5001"
    networks:
      - eazybank-network
    depends_on:
      - zipkin
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 90s
        max_attempts: 5
        window: 240s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:5003/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:5004/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/


  cards:
    image: densoftdev/cards:latest
    mem_reservation: 700m
    ports:
      - "5002:5002"
    networks:
      - eazybank-network
    depends_on:
      - zipkin
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 90s
        max_attempts: 5
        window: 240s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:5003/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:5004/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  gatewayserver:
    image: densoftdev/gatewayserver:latest
    mem_reservation: 700m
    ports:
      - "5005:5005"
    networks:
      - eazybank-network
    depends_on:
      - zipkin
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 5
        window: 300s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:5003/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:5004/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/



networks:
  eazybank-network: